version: '3.8'

services:
  nginx_service:
    image: nginx:1.21.6-alpine
    container_name: nginx_service
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw

  database:
    build: ./Database
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: smosit
      MYSQL_USER: admin
      MYSQL_PASSWORD: "123456"
    ports:
      - 3306:3306
    command:
      [--character-set-server=utf8, --collation-server=utf8_general_ci]
    volumes:
      - ./Database/data-mysql:/var/lib/mysql:rw
      - ./Database/sql-scripts:/docker-entrypoint-initdb.d/:rw

  backend:
    image: ghcr.io/ppitchanon/smosit-backend:latest
    container_name: backend
    restart: always
   
  frontend:
    image: ghcr.io/ppitchanon/smosit-frontend:latest
    container_name: frontend
    restart: always
    
networks:
  default:
    external:
      name: smosit-net
      